import dotenv
import os

dotenv.load_dotenv()


BOT_TOKEN = os.getenv("BOT_TOKEN")
POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_HOST = os.getenv("POSTGRES_HOST")
POSTGRES_DB = os.getenv("POSTGRES_DB")

DATABASE_URL = f"postgresql+asyncpg://{
    POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}/{POSTGRES_DB}"
SYNC_DATABASE_URL = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}/{POSTGRES_DB}"

PROJECT_NAME = os.getenv("PROJECT_NAME")
API_V1_STR = os.getenv("API_V1_STR")

# setting
GIVE_FIVE_VALUE = os.getenv("GIVE_FIVE_VALUE")
GIVE_FIVE_TO_REFERRER_VALUE = os.getenv("GIVE_FIVE_TO_REFERRER_VALUE")
INITIAL_BONUS_VALUE = os.getenv("INITIAL_BONUS_VALUE")
INITIAL_BONUS_WITH_PREMIUM_VALUE = os.getenv("INITIAL_BONUS_WITH_PREMIUM_VALUE")

BACKEND_CORS_ORIGINS=os.getenv("BACKEND_CORS_ORIGINS").split(",")
FRONTEND_HOST=os.getenv("FRONTEND_HOST")
